/**
 * District types. Every city (config/cities.ts) is a grid of blocks where each
 * char of its layout is one of these. Row 0 is north (negative Z).
 *
 * R residencial · V comunidade · C comércio · P praça · S várzea · I indústria
 * F centro financeiro · B base aérea · U sítio · W água (mar, rio, lago)
 * A praia · K centro histórico · Q superquadra · G esplanada · M floresta · L marco da cidade
 */
export type DistrictId = 'R' | 'V' | 'C' | 'P' | 'S' | 'I' | 'F' | 'B' | 'U' | 'W' | 'A' | 'K' | 'Q' | 'G' | 'M' | 'L';

/** Grid metrics shared by every city. */
export const GRID = {
  blockSize: 58,
  roadWidth: 12,
  sidewalk: 3,
} as const;

/** Blocks that are not dry land for roads: a road between two of them doesn't exist. */
export const WET: ReadonlySet<DistrictId> = new Set<DistrictId>(['W', 'A']);

export interface DistrictDef {
  id: DistrictId;
  name: string;
  area: number;
  /** Multiplies threat gained while abducting here. */
  threatMult: number;
  matterMult: number;
  groundColor: number;
  /** Weighted spawn table for loose street props. */
  props: ReadonlyArray<{ id: string; w: number }>;
  propDensity: number;
  /** Rare/special spawn table. */
  rares: ReadonlyArray<{ id: string; w: number }>;
  rareChance: number;
}

export const DISTRICTS: Record<DistrictId, DistrictDef> = {
  R: {
    id: 'R',
    name: 'Bairro Residencial',
    area: 1,
    threatMult: 1,
    matterMult: 1,
    groundColor: 0x7fae5a,
    propDensity: 1,
    props: [
      { id: 'lata', w: 10 },
      { id: 'garrafa', w: 6 },
      { id: 'chinelo', w: 3 },
      { id: 'caixa', w: 7 },
      { id: 'saco_lixo', w: 7 },
      { id: 'cone', w: 4 },
      { id: 'coco', w: 3 },
      { id: 'bola', w: 2 },
      { id: 'isopor', w: 2 },
      { id: 'engradado', w: 3 },
      { id: 'vaso', w: 3 },
      { id: 'cadeira', w: 6 },
      { id: 'mesa_bar', w: 2 },
      { id: 'bicicleta', w: 4 },
      { id: 'lixeira', w: 3 },
      { id: 'botijao', w: 2 },
      { id: 'carrinho_mercado', w: 1.5 },
      { id: 'churrasqueira', w: 1.5 },
      { id: 'moto', w: 2.5 },
      { id: 'mototaxi', w: 1 },
      { id: 'carrinho_pipoca', w: 0.6 },
      { id: 'orelhao', w: 0.6 },
      { id: 'coxinha', w: 2 },
      { id: 'guarana', w: 3 },
      { id: 'marmita', w: 2 },
      { id: 'pipa', w: 2 },
      { id: 'radinho', w: 1.5 },
      { id: 'vassoura', w: 2 },
      { id: 'garrafa_cafe', w: 1 },
      { id: 'ventilador', w: 1.5 },
      { id: 'tv_tubo', w: 1 },
      { id: 'carrinho_rolima', w: 1 },
      { id: 'gaiola', w: 1 },
      { id: 'sofa', w: 0.8 },
      { id: 'geladeira', w: 0.6 },
      { id: 'moto_entrega', w: 1 },
      { id: 'carrinho_picole', w: 0.5 },
      { id: 'pombo', w: 2 },
    ],
    rares: [
      { id: 'galinha_cosmica', w: 2 },
      { id: 'carro_dourado', w: 1 },
      { id: 'perua_alien', w: 0.6 },
      { id: 'et_varginha', w: 0.5 },
      { id: 'caramelo_dourado', w: 1 },
    ],
    rareChance: 0.12,
  },
  V: {
    id: 'V',
    name: 'Comunidade do Morro Azul',
    area: 1,
    threatMult: 1,
    matterMult: 1.1,
    groundColor: 0xb07a52,
    propDensity: 1.2,
    props: [
      { id: 'lata', w: 8 },
      { id: 'garrafa', w: 5 },
      { id: 'caixa', w: 5 },
      { id: 'saco_lixo', w: 6 },
      { id: 'cadeira', w: 6 },
      { id: 'mesa_bar', w: 3 },
      { id: 'caixa_som', w: 2 },
      { id: 'moto', w: 4 },
      { id: 'mototaxi', w: 3 },
      { id: 'bicicleta', w: 3 },
      { id: 'botijao', w: 3 },
      { id: 'engradado', w: 3 },
      { id: 'churrasqueira', w: 2 },
      { id: 'pipa', w: 5 },
      { id: 'coxinha', w: 2 },
      { id: 'marmita', w: 2 },
      { id: 'guarana', w: 2 },
      { id: 'radinho', w: 2 },
      { id: 'carrinho_rolima', w: 2 },
      { id: 'sofa', w: 1.5 },
      { id: 'geladeira', w: 1 },
      { id: 'tv_tubo', w: 1.5 },
      { id: 'pandeiro', w: 1.5 },
      { id: 'moto_entrega', w: 1.5 },
      { id: 'sinuca', w: 0.4 },
      { id: 'gaiola', w: 1 },
    ],
    rares: [
      { id: 'galinha_cosmica', w: 1 },
      { id: 'caramelo_dourado', w: 1 },
    ],
    rareChance: 0.1,
  },
  C: {
    id: 'C',
    name: 'Centro Comercial',
    area: 2,
    threatMult: 1.1,
    matterMult: 1,
    groundColor: 0x9aa08c,
    propDensity: 1,
    props: [
      { id: 'lata', w: 5 },
      { id: 'caixa', w: 5 },
      { id: 'saco_lixo', w: 3 },
      { id: 'cone', w: 3 },
      { id: 'lixeira', w: 4 },
      { id: 'cadeira', w: 4 },
      { id: 'mesa_bar', w: 2 },
      { id: 'carrinho_mercado', w: 3 },
      { id: 'bicicleta', w: 2 },
      { id: 'moto', w: 4 },
      { id: 'mototaxi', w: 2 },
      { id: 'carrinho_pipoca', w: 2 },
      { id: 'barraca_feira', w: 2 },
      { id: 'orelhao', w: 1.5 },
      { id: 'guarda_sol', w: 1.5 },
      { id: 'coxinha', w: 3 },
      { id: 'pao_queijo', w: 2 },
      { id: 'guarana', w: 2 },
      { id: 'copo_acai', w: 2 },
      { id: 'carrinho_churros', w: 1.2 },
      { id: 'carrinho_caldo', w: 0.8 },
      { id: 'carrinho_hotdog', w: 1.2 },
      { id: 'carrinho_picole', w: 1 },
      { id: 'caixa_eletronico', w: 0.8 },
      { id: 'moto_entrega', w: 2 },
      { id: 'pombo', w: 2 },
      { id: 'relogio_rua', w: 0.4 },
    ],
    rares: [
      { id: 'carro_dourado', w: 1 },
      { id: 'perua_alien', w: 1 },
    ],
    rareChance: 0.1,
  },
  P: {
    id: 'P',
    name: 'Praça da Aurora',
    area: 2,
    threatMult: 1,
    matterMult: 1,
    groundColor: 0x6aa84f,
    propDensity: 1,
    props: [
      { id: 'lata', w: 5 },
      { id: 'coco', w: 4 },
      { id: 'bola', w: 2 },
      { id: 'lixeira', w: 3 },
      { id: 'carrinho_pipoca', w: 2 },
      { id: 'guarda_sol', w: 2 },
      { id: 'bicicleta', w: 3 },
      { id: 'pombo', w: 6 },
      { id: 'pipa', w: 2 },
      { id: 'pao_queijo', w: 1 },
      { id: 'brigadeiro', w: 1 },
      { id: 'carrinho_churros', w: 1.2 },
      { id: 'carrinho_picole', w: 1.2 },
      { id: 'carrinho_hotdog', w: 0.8 },
    ],
    rares: [{ id: 'estatua', w: 1 }],
    rareChance: 0,
  },
  S: {
    id: 'S',
    name: 'Campo de Várzea',
    area: 1,
    threatMult: 1,
    matterMult: 1,
    groundColor: 0x6aa84f,
    propDensity: 0.6,
    props: [
      { id: 'lata', w: 5 },
      { id: 'garrafa', w: 3 },
      { id: 'isopor', w: 3 },
      { id: 'cadeira', w: 5 },
      { id: 'bola', w: 1 },
      { id: 'moto', w: 2 },
      { id: 'pipa', w: 3 },
      { id: 'guarana', w: 2 },
      { id: 'pandeiro', w: 1 },
      { id: 'carrinho_picole', w: 1 },
      { id: 'carrinho_hotdog', w: 0.8 },
      { id: 'radinho', w: 1 },
    ],
    rares: [
      { id: 'saci', w: 1 },
    ],
    rareChance: 0.06,
  },
  I: {
    id: 'I',
    name: 'Zona Industrial',
    area: 3,
    threatMult: 1.15,
    matterMult: 1.1,
    groundColor: 0x8d8a7f,
    propDensity: 0.8,
    props: [
      { id: 'caixa', w: 5 },
      { id: 'engradado', w: 4 },
      { id: 'cone', w: 5 },
      { id: 'botijao', w: 3 },
      { id: 'lixeira', w: 2 },
      { id: 'moto', w: 2 },
      { id: 'empilhadeira', w: 2 },
      { id: 'marmita', w: 3 },
      { id: 'garrafa_cafe', w: 2 },
      { id: 'vassoura', w: 2 },
      { id: 'cacamba', w: 1 },
    ],
    rares: [{ id: 'caminhao_conspiracao', w: 1 }],
    rareChance: 0.25,
  },
  F: {
    id: 'F',
    name: 'Centro Financeiro',
    area: 4,
    threatMult: 1.3,
    matterMult: 1.15,
    groundColor: 0x8f9a8c,
    propDensity: 0.8,
    props: [
      { id: 'lata', w: 3 },
      { id: 'lixeira', w: 4 },
      { id: 'cone', w: 3 },
      { id: 'caixa', w: 3 },
      { id: 'banco_praca', w: 2 },
      { id: 'moto', w: 3 },
      { id: 'carrinho_pipoca', w: 1 },
      { id: 'pao_queijo', w: 2 },
      { id: 'garrafa_cafe', w: 1.5 },
      { id: 'caixa_eletronico', w: 1.5 },
      { id: 'moto_entrega', w: 2 },
      { id: 'pombo', w: 3 },
      { id: 'relogio_rua', w: 0.6 },
    ],
    rares: [{ id: 'carro_dourado', w: 1 }],
    rareChance: 0.08,
  },
  B: {
    id: 'B',
    name: 'Base Aérea Sentinela',
    area: 5,
    threatMult: 2,
    matterMult: 1.5,
    groundColor: 0x8b8f6a,
    propDensity: 0.5,
    props: [
      { id: 'cone', w: 4 },
      { id: 'caixa', w: 3 },
      { id: 'botijao', w: 2 },
      { id: 'engradado', w: 3 },
      { id: 'marmita', w: 2 },
      { id: 'garrafa_cafe', w: 2 },
    ],
    rares: [{ id: 'antena_secreta', w: 1 }],
    rareChance: 0.35,
  },
  U: {
    id: 'U',
    name: 'Sítio da Periferia',
    area: 1,
    threatMult: 1,
    matterMult: 1,
    groundColor: 0x86b45b,
    propDensity: 0.6,
    props: [
      { id: 'galinha', w: 8 },
      { id: 'coco', w: 4 },
      { id: 'caixa', w: 2 },
      { id: 'cachorro', w: 2 },
      { id: 'bicicleta', w: 2 },
      { id: 'churrasqueira', w: 1 },
      { id: 'bode', w: 3 },
      { id: 'porco', w: 3 },
      { id: 'jegue', w: 1.5 },
      { id: 'tatu', w: 1.5 },
      { id: 'abacaxi', w: 2 },
      { id: 'melancia', w: 2 },
      { id: 'rapadura', w: 1 },
      { id: 'varal', w: 1.5 },
      { id: 'tanque', w: 1 },
      { id: 'rede_dormir', w: 1 },
      { id: 'filtro_barro', w: 1 },
      { id: 'mandacaru', w: 1 },
      { id: 'carroca', w: 0.6 },
      { id: 'trator', w: 0.5 },
    ],
    rares: [
      { id: 'vaca_dourada', w: 1 },
      { id: 'galinha_cosmica', w: 1 },
      { id: 'saci', w: 1 },
      { id: 'mula_sem_cabeca', w: 0.8 },
      { id: 'chupacabra', w: 1 },
    ],
    rareChance: 0.35,
  },
  W: {
    id: 'W',
    name: 'Águas',
    area: 1,
    threatMult: 1,
    matterMult: 1,
    groundColor: 0x2b6f8f,
    propDensity: 0,
    props: [],
    rares: [],
    rareChance: 0,
  },
  A: {
    id: 'A',
    name: 'Praia',
    area: 1,
    threatMult: 0.9,
    matterMult: 1.05,
    groundColor: 0xead9a4,
    propDensity: 1.2,
    props: [
      { id: 'lata', w: 8 },
      { id: 'coco', w: 8 },
      { id: 'chinelo', w: 5 },
      { id: 'isopor', w: 5 },
      { id: 'bola', w: 3 },
      { id: 'guarda_sol', w: 7 },
      { id: 'cadeira_praia', w: 7 },
      { id: 'prancha', w: 3 },
      { id: 'garrafa', w: 3 },
      { id: 'copo_acai', w: 3 },
      { id: 'melancia', w: 2 },
      { id: 'abacaxi', w: 1 },
      { id: 'carrinho_picole', w: 2 },
      { id: 'radinho', w: 1.5 },
      { id: 'guarana', w: 2 },
    ],
    rares: [{ id: 'galinha_cosmica', w: 1 }],
    rareChance: 0.06,
  },
  K: {
    id: 'K',
    name: 'Centro Histórico',
    area: 2,
    threatMult: 1.05,
    matterMult: 1.05,
    groundColor: 0xa89884,
    propDensity: 1.1,
    props: [
      { id: 'lata', w: 6 },
      { id: 'garrafa', w: 4 },
      { id: 'caixa', w: 3 },
      { id: 'cadeira', w: 6 },
      { id: 'mesa_bar', w: 4 },
      { id: 'carrinho_pipoca', w: 2 },
      { id: 'bicicleta', w: 2 },
      { id: 'lixeira', w: 3 },
      { id: 'vaso', w: 3 },
      { id: 'orelhao', w: 1 },
      { id: 'pandeiro', w: 2 },
      { id: 'berimbau', w: 1.5 },
      { id: 'tambor', w: 1.5 },
      { id: 'pombo', w: 3 },
      { id: 'brigadeiro', w: 1 },
      { id: 'sinuca', w: 0.3 },
      { id: 'carrinho_churros', w: 0.8 },
    ],
    rares: [{ id: 'estatua', w: 0.4 }],
    rareChance: 0.04,
  },
  Q: {
    id: 'Q',
    name: 'Superquadra',
    area: 3,
    threatMult: 1.05,
    matterMult: 1.05,
    groundColor: 0x86b35c,
    propDensity: 0.7,
    props: [
      { id: 'lata', w: 5 },
      { id: 'bola', w: 3 },
      { id: 'bicicleta', w: 4 },
      { id: 'banco_praca', w: 4 },
      { id: 'lixeira', w: 4 },
      { id: 'pequi', w: 5 },
      { id: 'cadeira', w: 2 },
      { id: 'moto', w: 2 },
      { id: 'pao_queijo', w: 2 },
      { id: 'pombo', w: 2 },
      { id: 'tamandua', w: 0.8 },
      { id: 'pipa', w: 1.5 },
      { id: 'carrinho_picole', w: 0.8 },
    ],
    rares: [{ id: 'pequi_radioativo', w: 1 }],
    rareChance: 0.08,
  },
  G: {
    id: 'G',
    name: 'Esplanada',
    area: 4,
    threatMult: 1.35,
    matterMult: 1.2,
    groundColor: 0x8cba5c,
    propDensity: 0.5,
    props: [
      { id: 'cone', w: 5 },
      { id: 'lixeira', w: 4 },
      { id: 'banco_praca', w: 3 },
      { id: 'bicicleta', w: 2 },
      { id: 'caixa', w: 3 },
      { id: 'pequi', w: 2 },
      { id: 'pombo', w: 2 },
      { id: 'garrafa_cafe', w: 1 },
      { id: 'tamandua', w: 0.6 },
    ],
    rares: [{ id: 'pequi_radioativo', w: 1 }],
    rareChance: 0.05,
  },
  M: {
    id: 'M',
    name: 'Floresta',
    area: 2,
    threatMult: 0.8,
    matterMult: 1.1,
    groundColor: 0x3f7f3a,
    propDensity: 0.8,
    props: [
      { id: 'coco', w: 3 },
      { id: 'arara', w: 5 },
      { id: 'capivara', w: 4 },
      { id: 'bananeira', w: 4 },
      { id: 'caixa', w: 1 },
      { id: 'tucano', w: 4 },
      { id: 'mico', w: 3 },
      { id: 'papagaio', w: 3 },
      { id: 'tatu', w: 2 },
      { id: 'onca', w: 0.8 },
      { id: 'abacaxi', w: 1 },
    ],
    rares: [
      { id: 'boto', w: 1 },
      { id: 'curupira', w: 1 },
      { id: 'boitata', w: 0.8 },
    ],
    rareChance: 0.12,
  },
  L: {
    id: 'L',
    name: 'Cartão-postal',
    area: 3,
    threatMult: 1.2,
    matterMult: 1.2,
    groundColor: 0xa7ab98,
    propDensity: 0.8,
    props: [
      { id: 'lata', w: 5 },
      { id: 'garrafa', w: 3 },
      { id: 'lixeira', w: 4 },
      { id: 'banco_praca', w: 3 },
      { id: 'carrinho_pipoca', w: 2 },
      { id: 'guarda_sol', w: 2 },
      { id: 'bicicleta', w: 2 },
      { id: 'pombo', w: 4 },
      { id: 'pipa', w: 1.5 },
      { id: 'carrinho_churros', w: 1 },
      { id: 'carrinho_picole', w: 1 },
      { id: 'pao_queijo', w: 1 },
    ],
    rares: [],
    rareChance: 0,
  },
};

/**
 * Fictional signs (Nova Aurora defaults). Every city swaps these 16 slots for its own,
 * see CityDef.signs. Humor stays ambient and organic.
 */
export const SHOP_SIGNS = [
  'BAR DO ET',
  'LANCHONETE 51',
  'DISCOS VOADORES AUTO PEÇAS',
  'PROMOÇÃO: 3 COXINHAS',
  'PADARIA AURORA',
  'MERCADINHO ÓRBITA',
  'AÇAÍ DA GALÁXIA',
  'SALÃO DA DONA NENÊ',
  'BORRACHARIA 24H',
  'FARMÁCIA POPULAR DO BAIRRO',
  'PASTELARIA ESTRELA',
  'CHAVEIRO & CIA',
  'ESPETINHO DO MARTE',
  'LOTÉRICA SORTE GRANDE',
  'OFICINA DO BIGODE',
  'ÓTICA VISÃO NOTURNA',
];

/** 5 billboard slots, swapped per city like the shop signs. */
export const BILLBOARD_ADS = [
  'DISCOS VOADORES AUTO PEÇAS',
  'COXINHA ESPACIAL — R$ 5',
  'VOTE NINGUÉM',
  'SEU CARRO SUMIU? SEGUROS AURORA',
  'NOVA AURORA TE ESPERA',
];
